    - name: Install dependencies
      apt: 
        state: present
        name:
         - python
         - python-setuptools
         - python-dev
         - build-essential
         - python-pip
         - python-mysqldb
         - python3-apt
