    - name: Install MySQL database
      apt:
        state:  present
        name: 
          - mysql-server
          - mysql-client
          - python-pymysql

    - name: Start Mysql Service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create Application Database
      mysql_db: name=employee_db state=present login_unix_socket=/var/run/mysqld/mysqld.sock

    - name: Create Application DB User
      mysql_user: name=db_user  password=password priv='*.*:ALL' host='%' state='present' login_unix_socket=/var/run/mysqld/mysqld.sock
