    - name: Install Python Flask dependencies
      pip:
        state: present
        name: 
          - flask
          - flask-mysql

    - name: Copy web-server code
      copy: src=app.py dest=/opt/app.py

    - name: Start web-application
      shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &